# Generated by Django 4.2.6 on 2023-10-25 19:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('namebooking', models.CharField(max_length=60)),
                ('datestart', models.DateTimeField()),
                ('datefinish', models.DateTimeField()),
                ('adress', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('typeexpense', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'expense',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='sight',
            fields=[
                ('sight_id', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('url', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'sight',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('typeticket', models.CharField(max_length=40)),
                ('datestart', models.DateTimeField()),
                ('datefinish', models.DateTimeField()),
                ('adressstart', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='traveltype',
            fields=[
                ('traveltype_id', models.AutoField(primary_key=True, serialize=False)),
                ('traveltypedescription', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'traveltype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='travelplan',
            fields=[
                ('travelplan_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('territory', models.CharField(max_length=100)),
                ('datestart', models.DateTimeField()),
                ('datefinish', models.DateTimeField()),
                ('quantitydays', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('gpxtrek', models.TextField(null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('traveltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.traveltype')),
            ],
            options={
                'db_table': 'travelplan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='travelplanticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.ticket')),
                ('travelplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelplan')),
            ],
            options={
                'unique_together': {('travelplan', 'ticket')},
            },
        ),
        migrations.CreateModel(
            name='travelplansight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.sight')),
                ('travelplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelplan')),
            ],
            options={
                'unique_together': {('travelplan', 'sight')},
            },
        ),
        migrations.CreateModel(
            name='travelplanexpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.expense')),
                ('travelplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelplan')),
            ],
            options={
                'unique_together': {('travelplan', 'expense')},
            },
        ),
        migrations.CreateModel(
            name='travelplanbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.booking')),
                ('travelplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelplan')),
            ],
            options={
                'unique_together': {('travelplan', 'booking')},
            },
        ),
    ]
