# Generated by Django 4.2.6 on 2023-12-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('namecurrency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'currency',
                'managed': True,
            },
        ),
    ]
