# Generated by Django 4.2.6 on 2023-11-12 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelplan_geo',
            fields=[
                ('travelplan_geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('gpxtrek', models.TextField(null=True)),
                ('graph_data', models.JSONField(blank=True, null=True)),
                ('geojson', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='gpxtrek',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='friends_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='moving_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='speed_midle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='speed_moving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='total_ascent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='total_descent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='total_distance_travelled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='total_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='travelplan',
            name='travelplan_geo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.travelplan_geo'),
            preserve_default=False,
        ),
    ]
