# Generated by Django 4.2.6 on 2023-11-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='description',
            fields=[
                ('descriptiond_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_descriptiond', models.CharField(max_length=6000)),
                ('media_1', models.CharField(blank=True, max_length=200, null=True)),
                ('media_2', models.CharField(blank=True, max_length=200, null=True)),
                ('media_3', models.CharField(blank=True, max_length=200, null=True)),
                ('media_4', models.CharField(blank=True, max_length=200, null=True)),
                ('media_5', models.CharField(blank=True, max_length=200, null=True)),
                ('media_6', models.CharField(blank=True, max_length=200, null=True)),
                ('media_7', models.CharField(blank=True, max_length=200, null=True)),
                ('media_8', models.CharField(blank=True, max_length=200, null=True)),
                ('media_9', models.CharField(blank=True, max_length=200, null=True)),
                ('media_10', models.CharField(blank=True, max_length=200, null=True)),
                ('media_11', models.CharField(blank=True, max_length=200, null=True)),
                ('media_12', models.CharField(blank=True, max_length=200, null=True)),
                ('media_13', models.CharField(blank=True, max_length=200, null=True)),
                ('media_14', models.CharField(blank=True, max_length=200, null=True)),
                ('media_15', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'description',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='description',
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='travelplandescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.description')),
                ('travelplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelplan')),
            ],
            options={
                'unique_together': {('travelplan', 'description')},
            },
        ),
    ]
