# Generated by Django 4.2.6 on 2023-11-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_description_remove_travelplan_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='media_11',
            new_name='description_media_1',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='media_12',
            new_name='description_media_10',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='media_14',
            new_name='description_media_2',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='media_13',
            new_name='description_media_3',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='media_15',
            new_name='description_media_4',
        ),
        migrations.AddField(
            model_name='description',
            name='description_media_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='description_media_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='description_media_7',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='description_media_8',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='description_media_9',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
