# Generated by Django 4.2.6 on 2023-12-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('namecountry', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'country',
                'managed': True,
            },
        ),
    ]
