# Generated by Django 4.2.6 on 2023-11-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_rename_media_11_description_description_media_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='title_descriptiond',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
