# Generated by Django 4.2.6 on 2023-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='namecountry',
            field=models.CharField(max_length=20),
        ),
    ]
