# Generated by Django 4.2.6 on 2023-12-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_country_namecountry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='country',
            new_name='countrytravel',
        ),
    ]
