# Generated by Django 4.2.6 on 2023-12-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_description_title_descriptiond'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='nameexpense',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
