# Generated by Django 4.2.6 on 2023-12-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_typeexpense_alter_expense_typeexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='currency',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
