# Generated by Django 4.2.6 on 2023-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_expense_currency_travelplan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='nameexpense',
            field=models.CharField(max_length=70),
        ),
    ]
