# Generated by Django 4.2.6 on 2023-12-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_expense_nameexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
