# Generated by Django 4.2.6 on 2023-12-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_expense_quantity_day_expense_quantity_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='full_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
