# Generated by Django 4.2.6 on 2023-11-18 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(help_text='Ваш пароль должен содержать не менее 8 символов и включать хотя бы один из следующих символов: @, &, $, %, !, #, *', max_length=128, validators=[user.validators.CustomPasswordValidator], verbose_name='password')),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_history', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertypedescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('usersurname', models.CharField(max_length=70)),
                ('userage', models.IntegerField(blank=True, null=True)),
                ('userstatuspay', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usertype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usertype')),
            ],
        ),
    ]
