# Generated by Django 4.2.6 on 2023-11-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_history',
            field=models.JSONField(default=list),
        ),
    ]
